name: bluetooth_enable
description: Flutter plugin to turn on bluetooth within app (Android only)
version: 2.0.0-null-safety
# authors: 
#   - Hui
homepage: https://github.com/huitingyeong/bluetooth_enable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.hui.bluetooth_enable
    pluginClass: BluetoothEnablePlugin
